# Generated by Django 4.2.3 on 2023-10-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codechecker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='no_of_uses',
            field=models.IntegerField(default=0, max_length=1),
        ),
    ]
