# Generated by Django 4.2.2 on 2023-11-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codechecker', '0003_record_number_alter_record_no_of_uses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
