# Generated by Django 4.2.3 on 2023-12-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codechecker', '0004_alter_record_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_title', models.CharField(max_length=50)),
                ('validation_field', models.CharField(max_length=50)),
                ('dataset', models.FileField(upload_to='datasets/')),
            ],
        ),
    ]
