# Generated by Django 4.2.3 on 2023-12-19 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codechecker', '0005_database'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.JSONField()),
                ('absent', models.JSONField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='codechecker.database')),
            ],
        ),
    ]
