# Generated by Django 4.2.3 on 2023-12-19 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codechecker', '0006_attendancerecords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecords',
            name='absent',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecords',
            name='database',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='codechecker.database'),
        ),
        migrations.AlterField(
            model_name='attendancerecords',
            name='present',
            field=models.JSONField(null=True),
        ),
    ]
