# Generated by Django 4.2.3 on 2023-12-19 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codechecker', '0007_alter_attendancerecords_absent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.JSONField(default=list)),
                ('absent', models.JSONField(default=list)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('database', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='codechecker.database')),
            ],
        ),
        migrations.DeleteModel(
            name='AttendanceRecords',
        ),
    ]
