# Generated by Django 4.2.3 on 2023-12-19 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codechecker', '0008_attendancerecord_delete_attendancerecords'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='checked_in',
            field=models.JSONField(default=dict),
        ),
    ]
