# Generated by Django 4.2.3 on 2024-01-02 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codechecker', '0009_attendancerecord_checked_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_title', models.CharField(max_length=50)),
                ('validation_field', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('dataset', models.FileField(upload_to='datasets/')),
            ],
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='database',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='codechecker.event'),
        ),
        migrations.DeleteModel(
            name='Database',
        ),
    ]
