# Generated by Django 4.2.3 on 2024-01-02 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codechecker', '0010_event_alter_attendancerecord_database_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancerecord',
            old_name='database',
            new_name='event',
        ),
    ]
