# Generated by Django 4.2.3 on 2024-01-02 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codechecker', '0011_rename_database_attendancerecord_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='database_title',
            new_name='event_title',
        ),
    ]
