# Generated by Django 4.2.3 on 2024-01-04 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('codechecker', '0013_alter_event_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recently_opened', models.JSONField(verbose_name=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
